version: "3.9"

services:
  api:
    build: ./backend
    container_name: pharma_classifier_api
    command: uvicorn main_api:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "18000:8000"
    volumes:
      - ./data:/app/data

  ui:
    build: ./frontend
    container_name: pharma_classifier_ui
    ports:
      - "18100:5173"
    depends_on:
      - api
