version: "3.9"

services:
  api:
    build: ./backend
    container_name: pharma_classifier_api
    command: uvicorn main_api:app --host 0.0.0.0 --port 8000
    ports:
      - "18000:8000"
    volumes:
      - ./data:/app/data
  ui:
    build: ./frontend
    container_name: pharma_classifier_ui
    ports:
      - "18100:5173"
    environment:
      - VITE_API_URL=http://localhost:18000
    depends_on:
      - api
